import Link from "next/link";
import { requireRole } from "@/lib/auth";
import { getTeacherResults, getTeacherStudents, getTeacherTests } from "@/lib/teacher";

export default async function TeacherWorkspace() {
  const user = await requireRole(["teacher", "admin"]);
  const [students, tests, results] = await Promise.all([getTeacherStudents(user.id), getTeacherTests(user.id), getTeacherResults(user.id)]);
  const gradedPercentages = results.filter((item) => item.score !== null && item.max_score !== null).map((item) => Number(item.score) / Math.max(Number(item.max_score), 1) * 100);
  const average = gradedPercentages.length ? Math.round(gradedPercentages.reduce((a, b) => a + b, 0) / gradedPercentages.length) : null;

  return <main className="workspace-page"><div className="container"><section className="dashboard-hero split"><div><span className="eyebrow">Teacher workspace</span><h1>Teach from a clearer control room.</h1><p>See your learner roster, build assessments and review outcomes without crossing student ownership boundaries.</p></div><Link href="/teacher/tests/new" className="primary-button">Create assessment →</Link></section><section className="metric-grid"><Link className="metric-card interactive" href="/teacher/students"><span>Students</span><strong>{students.length}</strong><small>learners assigned to you</small></Link><Link className="metric-card interactive" href="/teacher/tests"><span>Tests</span><strong>{tests.length}</strong><small>drafts and published assessments</small></Link><Link className="metric-card interactive" href="/teacher/results"><span>Graded results</span><strong>{results.length}</strong><small>server-graded outcomes</small></Link><div className="metric-card"><span>Average</span><strong>{average === null ? "—" : `${average}%`}</strong><small>across available graded results</small></div></section><section className="dashboard-grid two-column"><article className="surface-card"><div className="section-heading"><div><span className="eyebrow">Learners</span><h2>Know who needs attention.</h2></div><Link href="/teacher/students" className="text-link">Open roster →</Link></div>{students.slice(0,5).map((item) => <div key={item.student_id} className="focus-row"><div><strong>{item.profiles?.[0]?.display_name ?? "Student"}</strong><span>Assigned learner</span></div><span className="status-chip active">Active</span></div>)}{!students.length && <div className="empty-state">No students are assigned yet.</div>}</article><article className="surface-card"><div className="section-heading"><div><span className="eyebrow">Assessment</span><h2>Build and review deliberately.</h2></div><Link href="/teacher/tests" className="text-link">Open tests →</Link></div><div className="action-stack"><Link href="/teacher/tests" className="action-row"><span><b>Create or edit a test</b><small>Keep question content and publishing under teacher authorization.</small></span><b>→</b></Link><Link href="/teacher/results" className="action-row"><span><b>Review results</b><small>See outcomes for tests owned by your account.</small></span><b>→</b></Link></div></article></section></div></main>;
}